# Default values for uwsgi.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Extract to global variables those variables most
# susceptible to be overridden.
global:
  image:
    uwsgi: ""
    tag: "latest"
  dataSecrets:
  dataConfigMap:
  cloudSql:
    host: ""
  secrets:
    passwordDB: ""
    sentryDSN: ""
  configMap:
    databaseHost: "127.0.0.1"
    databasePort: "5432"
  celery:
    brokerUrl: ""
  databaseController:
    secret:
      shared: false
      name: db-secret

replicaCount: 1
strategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 0


deployment:
  labels:
    tier: web
  image:
    pullPolicy: Always
  probes:
    liveness:
      enabled: true
      command: /entrypoint.sh
      args: launch-liveness-probe
      delay: 45
      timeout: 5
      threshold: 5
      period: 30
      success: 1
    readiness:
      enabled: false
      command: /entrypoint.sh
      args: launch-readiness-probe
      delay: 10
      timeout: 5
      threshold: 5
      period: 30
      success: 1
  resources:
    limits:
      cpu: 250m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi
  sentry:
    enabled: true
  redis:
    host: ""
    port: "6379"
    database: "1"
  pgBouncer:
    enabled: true
    port: 6543
    targetPort: 5432
    poolMode: "transaction"
    maxClientConn: 128
    maxDBConnections: 2
    listenBacklog: 4096
  metrics:
    enabled: false
    prometheus: false


service:
    enabled: true
    type: NodePort
    externalPort: 80
    internalPort: 8080


configMap:
    enabled: true
    databaseName: ""
    databaseUser: ""
    enableSentry: "True"
    compressEnabled: "True"
    compressOffline: "True"
    allowedHosts: "*"


secrets:
  enabled: true
  type: Opaque


crons:
  enabled: false
  args:
    - run-crons


djangoRQ:
  enabled: false
  args:
    - run-rq


migrations:
  enabled: false
  args:
    - run-migrations


databaseController:
  enabled: false