apiVersion: v1
name: django-nginx-uwsgi
icon: https://apsl.github.io/kubernetes-charts/images/django-nginx-uwsgi.png
version: 0.4.3
keywords:
  - django
  - nginx
  - uwsgi
  - crons
  - rq
  - celery
  - celery-beat
description: >
    A Chart for a simple architecture of an app deploying over K8s using 'nginx' and 'uwsgi' in the same pod.
    So, it depends of 'nginx-uwsgi' packages for the app, 'uwsgi' for 'crons', 'rq' or 'celery' and 'redis' package.
mantainers:
  - name: Tomeu Canyelles
    email: bcanyelles@apsl.net
  - name: Pau Rul.lan
    email: prullan@apsl.net
  - name: Edu Herraiz
    email: eherraiz@apsl.net
  - name: Marc Tudurí
    email: mtuduri@apsl.net
