dependencies:
  - name: nginx-uwsgi
    version: 0.3.0
    repository: file://../nginx-uwsgi
    alias: app

  - name: uwsgi
    version: 0.3.0
    repository: file://../uwsgi
    alias: crons
    condition: crons.enabled

  - name: uwsgi
    version: 0.3.0
    repository: file://../uwsgi
    alias: rq
    condition: rq.enabled

  - name: uwsgi
    version: 0.3.0
    repository: file://../uwsgi
    alias: celery
    condition: celery.enabled

  - name: varnish
    version: 0.1.0
    repository: file://../varnish
    condition: varnish.enabled

  - name: redis
    version: 0.8.0
    repository: https://kubernetes-charts.storage.googleapis.com
    condition: redis.enabled

  - name: uwsgi
    version: 0.3.0
    repository: file://../uwsgi
    alias: migrations
    condition: migrations.enabled
