dependencies:
  - name: nginx-uwsgi
    version: 0.1.1
    repository: https://raw.githubusercontent.com/APSL/kubernetes-charts/prepare_deployments/packages/
    alias: app

  - name: uwsgi
    version: 0.1.1
    repository: https://raw.githubusercontent.com/APSL/kubernetes-charts/prepare_deployments/packages/
    alias: crons
    condition: crons.enabled

  - name: uwsgi
    version: 0.1.1
    repository: https://raw.githubusercontent.com/APSL/kubernetes-charts/prepare_deployments/packages/
    alias: rq
    condition: rq.enabled

  - name: uwsgi
    version: 0.1.1
    repository: https://raw.githubusercontent.com/APSL/kubernetes-charts/prepare_deployments/packages/
    alias: celery
    condition: celery.enabled

  - name: varnish
    version: 0.1.0
    repository: https://raw.githubusercontent.com/APSL/kubernetes-charts/prepare_deployments/packages/
    condition: varnish.enabled

  - name: redis
    version: 0.8.0
    repository: https://kubernetes-charts.storage.googleapis.com
    condition: redis.enabled