# Default values for django app
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
.commons: &commons
  secrets:
    enabled: false
  service:
    enabled: false
  configMap:
    enabled: false
  strategy:
    type: Recreate
    probes:
      liveness:
        enabled: false
      readiness:
        enabled: false


global:
  image:
    uwsgi: ""
    nginx: ""
    tag: ""
  dataSecrets:
  dataConfigMap:
  cloudSql:
    host: ""
  secrets:
    passwordDB: ""
    sentryDSN: ""
  configMap:
    databaseHost: "127.0.0.1"
    databasePort: "5432"
  databaseController:
    secret:
      shared: false


cronjob:
  enabled: true
  suspend: true
  schedule: "0 6 * * 1-5"
  migrations:
    enabled: true


app:
  deployment:
    pgBouncer:
      enabled: true


crons:
  enabled: true
  crons:
    enabled: true
  <<: *commons
  deployment:
    probes:
      liveness:
        enabled: false
      readiness:
        enabled: true


migrations:
  enabled: false
  migrations:
    enabled: true
  <<: *commons
  deployment:
    probes:
      liveness:
        enabled: false
      readiness:
        enabled: true


celery:
  enabled: false
  <<: *commons


celery-beat:
  enabled: false
  <<: *commons
  deployment:
    args:
      - run-celery-beat
    metrics:
      enabled: false

rq:
  enabled: false
  djangoRQ:
    enabled: true
  <<: *commons


redis:
  enabled: false
  image: redis:3.0.7
  usePassword: false
  persistence:
    enabled: false
  resources:
    limits:
      cpu: 50m
      memory: 256Mi
    requests:
      cpu: 50m
      memory: 128Mi


# BackendHost takes release name as a prefix: {{ RELEASE_NAME-backendHost }}
varnish:
  enabled: true
  backendHost: ""

