# Customizable uwsgi deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ template "fullname" . }}
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}

spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "fullname" . }}
      tier: {{ .Values.deployment.labels.tier }}
{{- if .Values.strategy }}
  strategy:
{{ toYaml .Values.strategy | indent 4 }}
{{- end }}
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
        tier: {{ .Values.deployment.labels.tier }}

# Almost every variable has a default value, but take care of with some others
# like: repository, secretKey, passwordDB, that are mandatory but depends of each app.
    spec:
      {{- if .Values.affinity }}
      affinity:
      # App affinity
{{ toYaml .Values.affinity | indent 8 }}
      {{- end }}
      containers:
# App container
        - name: {{ .Release.Name }}-uwsgi
          image: {{ .Values.global.image.uwsgi }}:{{ .Values.deployment.image.tag }}
          imagePullPolicy: {{ .Values.deployment.image.pullPolicy }}
          {{- if .Values.deployment.probes.liveness.enabled }}
          livenessProbe:
            exec:
              command:
                - {{ .Values.deployment.probes.liveness.command }}
                - {{ .Values.deployment.probes.liveness.args }}
            initialDelaySeconds: {{ .Values.deployment.probes.liveness.delay }}
            timeoutSeconds: {{ .Values.deployment.probes.liveness.timeout }}
            failureThreshold: {{ .Values.deployment.probes.liveness.threshold }}
            periodSeconds: {{ .Values.deployment.probes.liveness.period }}
            successThreshold: {{ .Values.deployment.probes.liveness.success }}
          {{- end }}
          {{- if .Values.deployment.probes.readiness.enabled }}
          readinessProbe:
            exec:
              command:
                - {{ .Values.deployment.probes.readiness.command }}
                - {{ .Values.deployment.probes.readiness.args }}
            initialDelaySeconds: {{ .Values.deployment.probes.readiness.delay }}
            timeoutSeconds: {{ .Values.deployment.probes.readiness.timeout }}
            failureThreshold: {{ .Values.deployment.probes.readiness.threshold }}
            periodSeconds: {{ .Values.deployment.probes.readiness.period }}
            successThreshold: {{ .Values.deployment.probes.readiness.success }}
          {{- end }}
          lifecycle:
            postStart:
              exec:
                command: ["cp", "-av", "/data/.", "/data-nginx/"]
# Definition of essentials environment variables. This could be provided from direct string,
# a secret key or a config map.
# The structure of Values are built so that you can define a set of secret keys and/or a set
# of config map to complete the most important environment variables.
# Take a look apps/template.yaml to know how specify it.
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}
            - secretRef:
                name: {{ .Release.Name }}
          volumeMounts:
            - name: data-nginx
              mountPath: /data-nginx
              readOnly: False
          resources:
{{ toYaml .Values.deployment.resources | indent 12 }}
# This configuration could be used as a app deployment or as a cron deployment, so you
# can specify in Values if you want one or the other configuration.
          {{- if .Values.crons.enabled }}
          args: {{ .Values.crons.args }}
          {{- end }}
        {{- if .Values.deployment.cloudsqlProxy.enabled }}

# Cloud SQL proxy container
# The default configuration configure a proxy to a persistent database using a proxy container,
# but you can disable it with <deployment.cloudsqlProxy.enabled> value.
# Note: Is mandatory have generated a new service account for the project and have create a secret
# with the `json` resultant file account.

        {{- if .Values.deployment.cloudsqlProxy.enabled }}
        - name: {{ .Values.deployment.cloudsqlProxy.name }}
          image: "gcr.io/cloudsql-docker/gce-proxy:{{ .Values.global.cloudsqlProxy.tag }}"
          imagePullPolicy: {{ .Values.deployment.cloudsqlProxy.pullPolicy }}
          {{- if .Values.global.cloudsqlProxy.ports }}
          ports:
{{ toYaml .Values.global.cloudsqlProxy.ports | indent 12 }}
          {{- end }}
          command:
            - /cloud_sql_proxy
            - --dir=/cloudsql
            - -instances={{ .Values.global.image.cloudsqlProxy.project }}:{{ .Values.global.image.cloudsqlProxy.zone }}:{{ .Values.global.image.cloudsqlProxy.name }}=tcp:{{ .Values.global.image.cloudsqlProxy.port }}
            - -credential_file=/secrets/cloudsql/{{ .Values.global.image.cloudsqlProxy.filename }}
          volumeMounts:
            - name: cloudsql-oauth-credentials
              mountPath: /secrets/cloudsql
              readOnly: True
            - name: ssl-certs
              mountPath: /etc/ssl/certs
        {{- end }}

# Nginx container
# The default configuration create the nginx container, but you can disable it with
# <deployment.nginx.enabled> value.
        {{- if .Values.deployment.nginx.enabled }}
        - name: {{ .Release.Name }}-nginx
          image: {{ .Values.global.image.nginx }}:{{ .Values.deployment.image.tag }}
          imagePullPolicy: {{ .Values.deployment.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.internalPort }}
          {{- if .Values.deployment.probes.livenessEnabled }}
          livenessProbe:
            httpGet:
              path: /nginx/healthz
              port: 80
            initialDelaySeconds: 30
            timeoutSeconds: 5
          {{- end }}
          {{- if .Values.deployment.probes.readinessEnabled }}
          readinessProbe:
            httpGet:
              path: /nginx/healthz
              port: 80
            initialDelaySeconds: 5
            timeoutSeconds: 5
          {{- end }}
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}
          volumeMounts:
            - name: data-nginx
              mountPath: /data
              readOnly: True
          resources:
{{ toYaml .Values.deployment.resources | indent 12 }}
        {{- end }}

      {{- if .Values.deployment.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.deployment.nodeSelector | indent 8 }}
      {{- end }}

      volumes:

        {{- if .Values.deployment.cloudsqlProxy.enabled }}
        - name: cloudsql-oauth-credentials
          secret:
            secretName: cloudsql-oauth-credentials
        - name: ssl-certs
          hostPath:
            path: /etc/ssl/certs
        {{- end }}

        - name: data-nginx
          emptyDir: {}
{{- end }}
