# Default values for celery.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Extract to global variables those variables most
# susceptible to be overridden.
global:
  image:
    uwsgi: ""
    tag: "latest"
  dataSecrets:
  dataConfigMap:
  cloudSql:
    host: ""
  celery:
    brokerUrl: ""
  databaseController:
    secret:
      shared: false
      name: db-secret

replicaCount: 1
strategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 0


deployment:
  labels:
    tier: celery
  image:
    pullPolicy: Always
  probes:
    liveness:
      enabled: true
      command: /entrypoint.sh
      args: launch-celery-liveness-probe
      delay: 45
      timeout: 5
      threshold: 5
      period: 30
      success: 1
    readiness:
      enabled: false
      command: /entrypoint.sh
      args: launch-readiness-probe
      delay: 10
      timeout: 5
      threshold: 5
      period: 30
      success: 1
  resources:
    limits:
      cpu: 250m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
  args:
    - run-celery
  sentry:
    enabled: true
  pgBouncer:
    enabled: true
    port: 6543
    targetPort: 5432
    poolMode: "transaction"
    maxClientConn: 128
    maxDBConnections: 2
    listenBacklog: 4096
  metrics:
    enabled: true
    prometheus: false

databaseController:
  enabled: false