# Default values for uwsgi, nginx and poxy sql.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Extract to global variables those variables most
# susceptible to be overridden.
global:
  image:
    uwsgi: ""
    nginx: ""
    tag: "latest"
  dataSecrets:
  dataConfigMap:
  cloudSql:
    host: ""
  celery:
    brokerUrl: ""
  databaseController:
    secret:
      shared: false
      name: db-secret

replicaCount: 1
strategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 0


deployment:
  labels:
    tier: web
  image:
    pullPolicy: Always
  probes:
    liveness:
      enabled: true
      command: /entrypoint.sh
      args: launch-liveness-probe
      delay: 45
      timeout: 5
      threshold: 5
      period: 30
      success: 1
    readiness:
      enabled: true
      command: /entrypoint.sh
      args: launch-readiness-probe
      delay: 10
      timeout: 5
      threshold: 5
      period: 30
      success: 1
  resources:
    limits:
      cpu: 250m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi
  sentry:
    enabled: true
  redis:
    host: ""
    port: "6379"
    database: "1"
  nginx:
    enabled: true
    ports:
      - name: http
        containerPort: 80
    probes:
      liveness:
        enabled: true
        httpPath: /nginx/healthz
        initialDelay: 30
        timeout: 5
      readiness:
        enabled: true
        httpPath: /nginx/healthz
        initialDelay: 5
        timeout: 5
    resources:
      requests:
        cpu: 10m
        memory: 10Mi
      limits:
        cpu: 50m
        memory: 50Mi
  pgBouncer:
    enabled: true
    port: 6543
    targetPort: 5432
    poolMode: "transaction"
    maxClientConn: 128
    maxDBConnections: 2
    listenBacklog: 4096
  metrics:
    enabled: true
    prometheus: false


service:
    enabled: true
    type: NodePort
    externalPort: 80
    internalPort: 8000


configMap:
    enabled: true
    uwsgiAddr: "127.0.0.1:8080"
    enableBasicAuth: "True"
    enable3wRedirect: "True"
    enableHttpsRedirect: "True"
    databaseHost: "127.0.0.1"
    databasePort: "5432"
    databaseName: ""
    databaseUser: ""
    enableSentry: "True"
    compressEnabled: "True"
    compressOffline: "True"
    allowedHosts: "*"


secrets:
  enabled: true
  type: Opaque
  sentryDSN: ""
  passwordDB: ""


crons:
  enabled: false
  args:
    - run-crons


databaseController:
  enabled: false
