{{- if .Values.configMap.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Release.Name }}
  labels:
    app: {{ template "fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  ENABLE_BASIC_AUTH: "{{ .Values.configMap.enableBasicAuth }}"
  ENABLE_3W_REDIRECT: "{{ .Values.configMap.enable3wRedirect }}"
  ENABLE_HTTPS_REDIRECT: "{{ .Values.configMap.enableHttpsRedirect }}"
  ALLOWED_HOSTS: "{{ .Values.configMap.allowedHosts }}"

  DATABASE_HOST: "{{ .Values.configMap.databaseHost }}"
  {{- if .Values.deployment.pgBouncer.enabled }}
  DATABASE_PORT: "{{ .Values.deployment.pgBouncer.port }}"
  {{- else }}
  DATABASE_PORT: "{{ .Values.configMap.databasePort }}"
  {{- end }}
  {{- if not .Values.databaseController.enabled }}
  DATABASE_NAME: "{{ .Values.configMap.databaseName }}"
  DATABASE_USER: "{{ .Values.configMap.databaseUser }}"
  {{- end }}

  COMPRESS_ENABLED: "{{ .Values.configMap.compressEnabled }}"
  COMPRESS_OFFLINE: "{{ .Values.configMap.compressOffline }}"

  SENTRY_ENABLED: "{{ .Values.configMap.enableSentry }}"

  REDIS_HOST: "{{ .Release.Name }}-redis"
  REDIS_PORT: "{{ .Values.deployment.redisPort }}"

  # Environment variables to configure celery
  {{- if .Values.celery.enabled }}
  CELERY_BACKEND_TYPE: "{{ .Values.celery.backend }}"
  CELERY_BACKEND_HOST: "{{ .Values.celery.host }}"
  CELERY_BACKEND_PORT: "{{ .Values.celery.port }}"
  CELERY_BACKEND_DATABASE: "{{ .Values.celery.db }}"
  {{- if .Values.celery.flowerAuth }}
  FLOWER_BASIC_AUTH: "{{ .Values.celery.flowerAuth }}"
  {{- end }}
  {{- end }}

  # Configure other environment variables
  {{- if .Values.global.dataConfigMap }}
  {{- range $configmap := .Values.global.dataConfigMap }}
  {{ $configmap.key }}: "{{ $configmap.value }}"
  {{- end }}
  {{- end }}
{{- end }}