{{- if .Values.configMap.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Release.Name }}
  labels:
    app: {{ template "fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  django.enableSentry: "{{ .Values.configMap.enableSentry }}"
  django.databaseHost: "{{ .Values.configMap.databaseHost }}"
  django.databasePort: "{{ .Values.configMap.databasePort }}"
  django.databaseName: "{{ .Values.configMap.databaseName }}"
  django.databaseUser: "{{ .Values.configMap.databaseUser }}"
  django.enableBasicAuth: "{{ .Values.configMap.enableBasicAuth }}"
  django.enableHttpsRedirect: "{{ .Values.configMap.enableHttpsRedirect }}"
  django.enable3wRedirect: "{{ .Values.configMap.enable3wRedirect }}"
{{- if .Values.global.dataConfigMap }}
{{- range $configmap := .Values.global.dataConfigMap }}
  {{ $configmap.key }}: "{{ $configmap.value }}"
{{- end }}
{{- end }}
{{- end }}