dependencies:
  - name: uwsgi
    version: 0.4.2
    repository: https://raw.githubusercontent.com/APSL/kubernetes-charts/master/packages
    alias: app

  - name: uwsgi
    version: 0.4.2
    repository: https://raw.githubusercontent.com/APSL/kubernetes-charts/master/packages
    alias: crons
    condition: crons.enabled

  - name: uwsgi
    version: 0.4.2
    repository: https://raw.githubusercontent.com/APSL/kubernetes-charts/master/packages
    alias: rq
    condition: rq.enabled

  - name: django-celery
    version: 0.1.0
    repository: https://raw.githubusercontent.com/APSL/kubernetes-charts/master/packages
    alias: celery
    condition: celery.enabled

  - name: varnish
    version: 0.1.0
    repository: https://raw.githubusercontent.com/APSL/kubernetes-charts/master/packages
    condition: varnish.enabled

  - name: redis
    version: 0.8.0
    repository: https://kubernetes-charts.storage.googleapis.com
    condition: redis.enabled

  - name: uwsgi
    version: 0.4.2
    repository: https://raw.githubusercontent.com/APSL/kubernetes-charts/master/packages
    alias: migrations
    condition: migrations.enabled
