# Default values for django app
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
.commons: &commons
  secrets:
    enabled: false
  service:
    enabled: false
  configMap:
    enabled: false


global:
  dataSecrets:
  dataConfigMap:
  image:
    uwsgi: ""


uwsgi:
  secrets:
    sentryDSN: ""


crons:
  enabled: true
  <<: *commons
  crons:
    enabled: true
  deployment:
    probes:
      liveness:
        enabled: false


celery:
  enabled: false
  <<: *commons
  celery:
    enabled: true
  deployment:
    probes:
      liveness:
        enabled: false
      readiness:
        enabled: false


rq:
  enabled: false
  <<: *commons
  djangoRQ:
    enabled: true
  deployment:
    probes:
      liveness:
        enabled: false
      readiness:
        enabled: false


migrations:
  enabled: true
  <<: *commons
  deployment:
    probes:
      liveness:
        enabled: false
    args:
      - run-migrations


redis:
  enabled: false
  image: redis:3.0.7
  usePassword: false
  persistence:
    enabled: false
  resources:
    limits:
      cpu: 50m
      memory: 256Mi
    requests:
      cpu: 50m
      memory: 128Mi


# BackendHost takes release name as a prefix: {{ RELEASE_NAME-backendHost }}
varnish:
  enabled: true
  backendHost: "uwsgi"