apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Release.Name }}
spec:
  type: ExternalName
  externalName: {{ .Values.lb.service.name }}.{{ .Values.lb.service.namespace }}.svc.cluster.local
  ports:
    - port: 80
      name: http
      targetPort: 80
