apiVersion: v1
name: nginx
version: 0.1.0
keywords:
  - template
  - nginx
description: A Helm chart for a simple deployment of nginx server over Kubernetes.
mantainers:
  - name: Tomeu Canyelles
    email: bcanyelles@apsl.net
  - name: Pau Rul.lan
    email: prullan@apsl.net
  - name: Edu Herraiz
    email: eherraiz@apsl.net
