apiVersion: v1
name: varnish
icon: https://apsl.github.io/kubernetes-charts/images/varnish.png
version: 0.1.0
keywords:
  - template
  - varnish
description: A Chart for a varnish deployment.
mantainers:
  - name: Tomeu Canyelles
    email: bcanyelles@apsl.net
  - name: Pau Rul.lan
    email: prullan@apsl.net
  - name: Edu Herraiz
    email: eherraiz@apsl.net
  - name: Marc Tudurí
    email: mtuduri@apsl.net
