{{- if .Values.secrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Release.Namespace }}
  name: cloudsql-oauth-credentials
  labels:
    app: {{ template "fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: {{ .Values.secrets.type }}
data:
  {{ .Values.global.image.cloudsqlProxy.filename }}: "{{ .Values.secrets.b64cloudSQLCredentials }}"
{{- end }}